# Message types: Client→Server
AUTH = "AUTH"
SET_DESC = "SET_DESC"
PLACE_ITEM = "PLACE_ITEM"
REMOVE_ITEM = "REMOVE_ITEM"
LOOK = "LOOK"
WHO = "WHO"
LIST = "LIST"
KNOCK = "KNOCK"
KNOCK_REPLY = "KNOCK_REPLY"
ENTER = "ENTER"
SAY = "SAY"
WHISPER = "WHISPER"
HOME = "HOME"

# Message types: Server→Client
AUTH_OK = "AUTH_OK"
AUTH_FAIL = "AUTH_FAIL"
DESC_UPDATED = "DESC_UPDATED"
ITEM_PLACED = "ITEM_PLACED"
ITEM_REMOVED = "ITEM_REMOVED"
LOOK_RESULT = "LOOK_RESULT"
WHO_RESULT = "WHO_RESULT"
LIST_RESULT = "LIST_RESULT"
KNOCK_RECEIVED = "KNOCK_RECEIVED"
KNOCK_ACCEPTED = "KNOCK_ACCEPTED"
KNOCK_REJECTED = "KNOCK_REJECTED"
ENTER_OK = "ENTER_OK"
VISITOR_JOINED = "VISITOR_JOINED"
VISITOR_LEFT = "VISITOR_LEFT"
SAID = "SAID"
WHISPERED = "WHISPERED"
HOME_OK = "HOME_OK"
ERROR = "ERROR"

# Gateway push types (not forwarded to pending_response)
PUSH_TYPES = {
    SAID, WHISPERED, KNOCK_RECEIVED, KNOCK_ACCEPTED, KNOCK_REJECTED,
    VISITOR_JOINED, VISITOR_LEFT,
}

# Gateway response types (forwarded to pending_response)
RESPONSE_TYPES = {
    AUTH_OK, AUTH_FAIL, DESC_UPDATED, ITEM_PLACED, ITEM_REMOVED,
    LOOK_RESULT, WHO_RESULT, LIST_RESULT, ENTER_OK, HOME_OK, ERROR,
}
